name: cooler_mdlz
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.1.4
  http: ^0.13.5

  #Utils
  json_annotation: ^4.7.0
  json_serializable: ^6.4.0
  build_runner: ^2.2.1
  platform_device_id: ^1.0.1
  device_info_plus: ^4.1.2
  package_info_plus: ^2.0.0
  intl: ^0.18.1
  uuid: ^3.0.6
  connectivity_plus: ^2.3.9
  shared_preferences: ^2.0.15
  geolocator: ^9.0.1
  device_information: ^0.0.4
  permission_handler: ^10.2.0
  url_launcher: ^6.1.5
  sqflite: ^2.0.3
  path: ^1.8.2
  dio: ^4.0.6

  #UI
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  flutter_svg: ^1.1.5
  dotted_border: ^2.0.0+2
  dotted_line: ^3.1.0
  qr_code_scanner: ^1.0.1
  firebase_core: ^2.0.0
  path_provider: ^2.0.11
  image_picker: ^0.8.6
  flutter_datetime_picker: ^1.5.1
  pull_to_refresh: ^2.0.0
  google_maps_flutter: ^2.1.10
  image_watermark: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/icons/

  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
